### ISSUE TITLE
svelte not updating

### ISSUE THREAD

**Issue by jeffhargarten** [striblab/generator-striblab#3]
Whenever making a change to a svelte HTML template, Browserify doesn't fire. It also doesn't seem to compile the project's HTML at all unless I quit and `gulp develop` again. Javascript and SCSS changes update fine, it's just the HTML templates acting wonky

**Comment by zzolo** [comment]
I fixed this recently.  I think if you update to the newest version, `0.2.1`, it should be all good.

If you need to fix a project you made, you just need to update the Gulp watch process to look at the `templates` directory, not the `pages`.  See the first part of this commit:
https://github.com/striblab/generator-striblab/commit/87c14abf48212a4ee2ba8b9e130eb601df2232a0
