### ISSUE TITLE
adding ability to use versioning for gulp publish --staging

### ISSUE THREAD

**Issue by StribDavoflav** [striblab/generator-striblab#4]
Curious if we could publish versions of projects when using gulp publish --staging.

This would allow us to keep versions of progress throughout the creation portion of a project; allowing stakeholders to compare earlier versions.

My idea would be that we would use a command like 'gulp publish --staging --versioning' for project ExampleProject.

It would then publish ExampleProject to a directory inside http://static.startribune.com/news/projects-staging/all/ExampleProject called Version1 which would be a snapshot of all assets at that time.  If the --versioning was used again it would be the Version2.  

Thoughts?

**Comment by zzolo** [comment]
Yeah, this is a great idea.  Shouldn't be a hard lift.  Just a matter of reading that option, then adding a timestamp or version to the S3 location.

We would want to make sure that versioning doesn't work for production deploy/publish as having multiple versions out there for that purpose doesn't make sense and could cause confusion.

**Comment by zzolo** [comment]
Ok, so this should be in there:
https://github.com/striblab/generator-striblab/commit/0a91ed61082255c1fd438182c8a769bf2577c0b3

All you have to do is add `--publish-version` to a `deploy` or `publish` command.  If left without a value, it will use today's date.  Or you can do something more specific like `gulp deploy --staging --publish-version=awesome-feature-testing`.

And you can use it with open to have it open in the browser: `gulp publish:open --staging --publish-version=special`
